name: code_initial
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get:
  google_fonts:
  another_flutter_splash_screen:
  pinput: ^6.0.1
  sqflite: ^2.3.0
  path: ^1.9.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  confetti: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/vestigo_logo.png
  min_sdk_android: 21


